name: "kreed-moments"
channels:
  - conda-forge
  - pytorch
  - pyg
dependencies:
  - python=3.9
  - pytorch==2.2
  - cpuonly
  - lightning
  - pyg
  - geomstats
  - pydantic<2
  - pydantic-cli
  - wandb
  - rdkit
  - py3dmol
  - einops
  - numpy
  - scipy=1.11.2
  - matplotlib
  - pybind11
  - eigen
  - xtb
  - gdown
  - isort
  - black
  - jupyter
  - notebook
  - ipywidgets